== Description

This overlay is a work in progress.

It is intended for use with amd64 systems with a strong focus on the musl/llvm
profile.

=== Notes

==== net-libs/nodejs
1. Removes gcc dependency.

==== www-client/chromium

[WARNING]
====
This will not compile against musl unless you have cdefs.h, tree.h and
execinfo.h. These libraries **should not be installed** on your system as it
will cause conflicts with build systems. In the future I will implement a
function within the ebuild that will sort this out.
====

1. Includes patches for musl.
2. Includes hardening patches from hardened-chromium and Vanadium.

=== Acknowledgements

==== www-client/chromium
1. https://github.com/12101111/overlay
2. https://github.com/secureblue/hardened-chromium
3. https://github.com/GrapheneOS/Vanadium

=== Licenses

[WARNING]
====
Since gitea does not support relative links for asciidoc files, I have used
absolute links instead. This means that they will not work for mirrors.
====

This project uses third-party patches. Their licenses can be found in the
https://src.reticentadmin.com/aryan/haoyis-gentoo-overlay/src/branch/main/licenses/[licenses] directory.

* https://src.reticentadmin.com/aryan/haoyis-gentoo-overlay/src/branch/main/licenses/hardened-chromium/[hardened-chromium]: Patches from SecureBlue's hardened-chromium.
* https://src.reticentadmin.com/aryan/haoyis-gentoo-overlay/src/branch/main/licenses/vanadium/[vanadium]: Patches from GrapheneOS's Vanadium.
